### ISSUE TITLE
Build the demo application

### ISSUE THREAD

**Issue by jordan-heemskerk** [RobertLeahy/SENG499#118]

**Comment by RobertLeahy** [comment]
We want (as per discussion with @jordan-heemskerk):
- Ability to switch between file system depth frames and actual OpenNI/OpenNI2 camera

Comment on this issue with further features/ideas.

**Comment by RobertLeahy** [comment]
I've added the ability to switch between file system depth frames and an actual depth camera.

See 490cfc7069fb6dd3ae35ddbc084b8099734c9942.

**Comment by RobertLeahy** [comment]
@jordan-heemskerk we need to iron out what actual implementations of `dynfu::pose_estimation_pipeline_block`, `dynfu::update_reconstruction_pipeline_block`, and `surface_prediction_pipeline_block` we're going to use, and what parameters etc. their constructors should be passed.

Right now I can't do anything useful with the client because these aren't being created/added to the pipeline, so it's incomplete and I just get:

```
PS Z:\UVic\2016\Summer\SENG499> bin/client --dataset=./data/test/msrc_file_system_depth_device
ERROR: Incomplete Kinect Fusion pipeline
```

**Comment by jordan-heemskerk** [comment]
@RobertLeahy I would say the implementations that we will be using, at this point, will be `dynfu::kinect_fusion_eigen_pose_estimation_pipeline_block`, `dynfu::kinect_fusion_opencl_update_reconstruction_pipeline_block`, and (when it is complete) `dynfu::kinect_fusion_opencl_surface_prediction_pipeline_block`. If we somehow have enough time, we could try to implement a `dynfu::kinect_fusion_opencl_pose_estimation_pipeline_block` but we may never have a chance.
