### ISSUE TITLE
Use fixed point or half float for TSDF values to save space

### ISSUE THREAD

**Issue by jordan-heemskerk** [RobertLeahy/SENG499#199]
This should hopefully allow us to run at 512x512x512 resolution, which currently overflows the memory capacity of even Robert's graphics card.

**Comment by RobertLeahy** [comment]
Given [this](http://developer.amd.com/tools-and-sdks/opencl-zone/amd-accelerated-parallel-processing-app-sdk/opencl-optimization-guide/#50401315_pgfId-533785) it seems to me that we should avoid integer operations (i.e. fixed point) wherever possible.

Half float is worth looking into.  The only issue is going to be that we expose a way to download the TSDF to the CPU (as we do with everything for generality) and I'm not sure there's a datatype in C++ (as an extension on the compilers we're using or otherwise) for half floats.

There was [a proposal on SG14 to introduce a `std::float16_t` type](https://groups.google.com/a/isocpp.org/d/msg/sg14/1QPYtQLQ0eA/4Oyih2_GAAAJ), but I don't think it's gone anywhere...

**Comment by jordan-heemskerk** [comment]
> Generally, the throughput and latency for 32-bit integer operations is the same as for single-precision floating point operations.

That's from your link. Sounds like they are the same latency?

**Comment by RobertLeahy** [comment]
The table at the top of the section I linked to suggests floating point add has half the latency of integer add.  I took that as meaning the throughput was much greater on floating point operations.

**Comment by RobertLeahy** [comment]
[This may be useful.](http://half.sourceforge.net/)
