### ISSUE TITLE
Prototype Raycasting the TSDF to compute the global model V and N maps

### ISSUE THREAD

**Issue by jordan-heemskerk** [RobertLeahy/SENG499#31]

**Comment by JorinDW** [comment]
//need to render the surface in the zero level set which is done by using the current estimate of the camera's position in space Tg,k.
//The surface prediction is stored as a vertex and normal map Vk and Nk.
//Each pixel's ray is calculated as Tg,k K^-1 u and marched through space when a zero crossing is encountered. +ve to -ve crossings indicate camera facing normals, and -ve to +ve crossings indicate away-from-camera facing normals. The only other case is when you exit the far side of the working volume. -ve to +ve and out-of-back both result in non-values so nothing is displayed in those cases.
//To calculate the normal of points where a +ve to -ve transition is encountered we perform three derivatives on the surface. (eqn 14)
//We perform scaling on these derivatives to account for differently sized voxels and reconstruction dimensions. What scaling?
//We get bounded time for pixel rendering since the plausible distances that a pixel can be is between .4 and 8 meters.
//We are going to use ray skipping to eliminate wasted passes. In this we utilize the fact that near F(p)=0 we have a good estimation of the SDF. We can then jump by mu each iteration and still know that when we go from +ve to -ve we have crossed the boundary of the SDF.
//once we have the general (mu) area between t and t + delta t, we can then acquire the more specific location between t and delta t which we can use as our rendering location. (eqn 15)

**Pseudo Code Version**
//things that we need to have access to
// -tsdf
// -vertex map
// -normal map
// -camera position in current frame
// -camera characteristics

//need to create a ray casting derived from each pixel normal of the camera sensor plane into the scene.
//do this by getting the camera's current position and the direction that it is pointing from T, and the number of pixels and camera details from K.
//calculate the normal of the sensor plane at each pixel.

```
for(each pixel){
    GlobalNormalMap(pixel) = NAN;//or other value that is non-value
    GlobalVertexMap(pixel) = NAN;//or other value that is non-value
    vector3 planeNormal = math with T and K matrix (at pixel location)
      for(check signChangeFound or planeNormal > maxDistance or SDFfound; planeNormal += mu){
            if(planeNormal negative to positive) break;//discard value (leave as NAN)
            if(planeNormal greater than max) break;//discard value (leave as NAN)   
            if(planeNormal positive to negative){
                  SDFfound = true; 
            }
      }
      GlobalNormalMap(pixel) = (eqn 14)
      GlobalVertexMap(pixel) = (eqn 15)
}
```

**Comment by JorinDW** [comment]
Anyone working on this already? I was going to take it on

**Comment by JorinDW** [comment]
@RobertLeahy @jordan-heemskerk

**Comment by jordan-heemskerk** [comment]
Ya see the branch for it
On Jul 11, 2016 10:25 AM, 4444jw4444 notifications@github.com wrote:Anyone working on this already? I was going to take it on

**Comment by jordan-heemskerk** [comment]
We will use the frame-to-frame transform instead of the frame-to-model transform since we are running out of time

See #130

**Comment by jordan-heemskerk** [comment]
As per @ataiya, the frame-to-frame transform is highly unlikely to work. We are going to bring this back into the scope of the project.

**Comment by RobertLeahy** [comment]
See #142.

**Comment by RobertLeahy** [comment]
Getting vertices and normals from raycasting the TSDF:

Vertices:
![image](https://cloud.githubusercontent.com/assets/648276/16939524/56008404-4d37-11e6-845d-f9b042ae03bc.png)

Normals:
![image](https://cloud.githubusercontent.com/assets/648276/16939509/26264ff2-4d37-11e6-9f1c-92445d38de13.png)

See: e6dd4b0b46999e84cc8179ab4c2692c946cede5a.

We may need to look into why the heads are dominated by invalid normals, keeping in mind that this is only data from a single frame.

**Comment by jordan-heemskerk** [comment]
Note that PCL uses 80% of the truncation distance for their step size in raycasting.

https://github.com/PointCloudLibrary/pcl/blob/master/gpu/kinfu/src/cuda/ray_caster.cu#L299

**Comment by jordan-heemskerk** [comment]
We can't seem to get the raycaster to work well with 80% of the truncation distance for the step size.

**Comment by RobertLeahy** [comment]
Specifically things worked best with `STEP_SIZE` at 0.08 and `mu` at 5:

![image](https://cloud.githubusercontent.com/assets/648276/16940034/ad691b30-4d3b-11e6-80f5-9072dd2d893b.png)
