### ISSUE TITLE
What is the pi function in the TSDF generation?

### ISSUE THREAD

**Issue by jordan-heemskerk** [RobertLeahy/SENG499#71]

**Comment by jordan-heemskerk** [comment]
@ataiya In Section 3.3 of Kinect Fusion, an extensive formula is given to compute the TSDF. Equation 8 makes reference to a "pi" function. The only thing that I can find about this "pi" function is in Section 3.1:

> The function `q=pi(p)` performs perspective projection of `p` (an element of R3), including dehomogenisation to obtain `q` (an element of R2).

Is this "pi"  function derived from the camera parameters? Or is it simply dividing through by the z component to "dehomogenize"? Something else?

**Comment by jordan-heemskerk** [comment]
https://github.com/RobertLeahy/DynFu/blob/%2360-tsdf/cl/tsdf.cl#L44

**Comment by taiya** [comment]
Hi Jordan, remember 305? To compute perspective transformation we used the 4th components of the homogeneous coordinates. So to invert the transformation and get a 3D point from a 2D pixel you have to have to apply the same process, except in the opposite direction. This snapshot summarizes the process: https://www.dropbox.com/s/6vq1baq0zem43y9/Screenshot%202016-05-25%2013.41.10.png?dl=0

Each sensor is equipped with an "intrinsics" calibration matrix (3x3 homogeneous). This matrix contains the focal length along the diagonal, as well as the camera offset in the third column.

p.s. Any reason for doing matrix algebra by hand (very easy to make mistakes) rather than using a matrix library?

**Comment by jordan-heemskerk** [comment]
Thanks @ataiya . Not quite sure I'm 100% grasping this so maybe we can quickly touch on it in person. Aren't we going from 3D to 2D, not 2D to 3D in this "pi" function? In that case, we just divide through by the z component, right?

That is OpenCL C code above, which doesn't support Matrix*Vector operations. I toyed with writing a routine to do it, but this seemed like it may be more efficient. (Save on multiplications by 1 and such). That's very rough code right now.

**Comment by taiya** [comment]
Hope I covered all the core concepts today (for details, see the HTrack code).
I see regarding OpenCL, didn't notice it was compute code.
No support for GLM? (CUDA has support)

I am also surprised OpenCL doesn't have mat4 support like GLSL does?

**Comment by jordan-heemskerk** [comment]
See #72

**Comment by jordan-heemskerk** [comment]
Doesn't look like GLM supports OpenCL yet. OpenCL definitely does not support the mat4 type.
